// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://undgrufyltlzrdiauyvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuZGdydWZ5bHRsenJkaWF1eXZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NTg0NjAsImV4cCI6MjA2NTQzNDQ2MH0.OvqDv9a-ZLJxp5c89Ya53fwxBtL-1HqK8l9AE3wjos8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);