
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

const SUPABASE_URL = "https://iqreoormklgcbvfthwma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxcmVvb3Jta2xnY2J2ZnRod21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MTIzODYsImV4cCI6MjA2NTM4ODM4Nn0.gy6o7inFpqXnEN0TejnEQ0HmCMcw6NMe9fQ1dpczmjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
